if(NOT DEFINED LAUNCHER OR NOT DEFINED EXPECT_NATIVE_WAYLAND)
  message(FATAL_ERROR "LAUNCHER and EXPECT_NATIVE_WAYLAND are required")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "LC_ALL=C" readelf --wide --dynamic "${LAUNCHER}"
  RESULT_VARIABLE readelf_status
  OUTPUT_VARIABLE dynamic_section
  ERROR_VARIABLE readelf_error
)
if(NOT readelf_status EQUAL 0)
  message(FATAL_ERROR "readelf failed for ${LAUNCHER}:\n${readelf_error}")
endif()
if(NOT dynamic_section MATCHES "\\(RUNPATH\\).*\\[\\$ORIGIN\\]")
  message(FATAL_ERROR "${LAUNCHER} does not use an exact $ORIGIN runtime search path")
endif()

string(REGEX MATCHALL "Shared library: \\[[^]]+\\]" needed_entries "${dynamic_section}")
set(lynx_count 0)
set(egl_count 0)
set(wayland_client_count 0)
set(wayland_egl_count 0)
set(xkbcommon_count 0)
foreach(entry IN LISTS needed_entries)
  string(REGEX REPLACE ".*\\[([^]]+)\\]" "\\1" library "${entry}")
  if(library STREQUAL "liblynx.so")
    math(EXPR lynx_count "${lynx_count} + 1")
  elseif(library MATCHES "^libEGL\\.so($|\\.)")
    math(EXPR egl_count "${egl_count} + 1")
  elseif(library MATCHES "^libwayland-client\\.so($|\\.)")
    math(EXPR wayland_client_count "${wayland_client_count} + 1")
  elseif(library MATCHES "^libwayland-egl\\.so($|\\.)")
    math(EXPR wayland_egl_count "${wayland_egl_count} + 1")
  elseif(library MATCHES "^libxkbcommon\\.so($|\\.)")
    math(EXPR xkbcommon_count "${xkbcommon_count} + 1")
  elseif(library MATCHES "^libglfw")
    message(FATAL_ERROR "${LAUNCHER} dynamically links forbidden GLFW library ${library}")
  elseif(NOT library MATCHES "^(libX11|libGLX|libOpenGL|libEGL|libwayland-client|libwayland-egl|libxkbcommon|libffi|libstdc\\+\\+|libgcc_s|libm|libc|ld-linux-x86-64)\\.so($|\\.)")
    message(FATAL_ERROR "${LAUNCHER} has unexpected direct dependency ${library}")
  endif()
endforeach()
if(NOT lynx_count EQUAL 1)
  message(FATAL_ERROR "${LAUNCHER} must have exactly one liblynx.so dependency, found ${lynx_count}")
endif()
if(EXPECT_NATIVE_WAYLAND)
  set(expected_native_count 1)
else()
  set(expected_native_count 0)
endif()
foreach(dependency IN ITEMS egl wayland_client wayland_egl xkbcommon)
  if(NOT ${dependency}_count EQUAL expected_native_count)
    message(FATAL_ERROR
      "${LAUNCHER} must have ${expected_native_count} direct ${dependency} dependencies, found ${${dependency}_count}")
  endif()
endforeach()
